package com.br.itsingular.enums;

import lombok.Getter;

@Getter
public enum ClientesParceiros {

	VERTEM, ACERTE_CONSORCIOS, IT_SINGULAR, ODONTOPREV, SBT, TIVIT, TRANSFOLHA, FOLHA_SP, SAINT_GOBAN, VIA_VAREJO, GPA,
	ESTAPAR, BANCO_PAN, UNIMETAL, BANCO_SAFRA, PORTO_SEGURO, EMBRACON, SESCON, JEQUITI, POINTER, BRADESCO, ALLIANZ,
	REDHAT, AWS, CIELO, ELO, CLARO, BIZ, NEWCON, BANCO_BRADESCO_SEGUROS, BANCO_ABC, BANCO_ORIGINAL, RIACHUELO;

	private String clientes;

}
