package com.br.itsingular.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum TipoCargo {

	ACESS,
	ADMINISTRADOR,
	ADMINISTRADOR_REDES,
	AGILE_COACH,
	ANALISTA,
	ANALISTA_AUTOMACAO,
	ANALISTA_BANCO_DADOS,
	ANALISTA_BI,
	ANALISTA_INFRAESTRUTURA,
	ANALISTA_NEGOCIOS,
	ANALISTA_PROCESSOS,
	ANALISTA_QUALIDADE,
	ANALISTA_ReS,
	ANALISTA_REDES,
	ANALISTA_REQUISITOS,
	ANALISTA_RH,
	ANALISTA_SEGURANCA,
	ANALISTA_SISTEMAS,
	ANALISTA_SUPORTE,
	ANALISTA_SUSTENTACAO,
	ANALISTA_TESTES,
	ANALISTA_FINANCEIRO,
	ARQUITETO,
	ARQUITETO_APLICACAO,
	ARQUITETO_DADOS,
	ARQUITETO_REDES,
	ARQUITETO_SOLUCAO,
	ASSISTENTE,
	CONSULTOR,
	CONSULTOR_DEMANDAS,
	COORDENADOR,
	COORDENADOR_ARQUITETOS,
	COORDENADOR_TI,
	DBA,
	DESENVOLVEDOR,
	DESENVOLVEDOR_BACK_END,
	DESENVOLVEDOR_FRONT_END,
	DESENVOLVEDOR_FULL_STACK,
	DESENVOLVEDOR_MOBILE,
	DEVOPS,
	DEVSECOPS,
	ENGENHEIRO_DADOS,
	ENGENHEIRO_SOFTWARE,
	ENGENHEIRO_SEGURANCA,
	ESPECIALISTA,
	ESTAGIARIO,
	GERENTE_PROJETOS,
	LIDER_PROJETOS,
	LIDER_TECNICO,
	PMO,
	PO,
	QA,
	HELP_DESK,
	SCHEDULLER,
	SM,
	WEB_DESIGNER;

	private String tipoCargo;
	
}
